def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project! 


linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
use_frameworks! :linkage => linkage.to_sym
end



# Add you Notification Extension dependencies
# target 'notificationSetup' do
#   pod 'react-native-rainbow-module', :path => '../node_modules/react-native-rainbow-module'
# end

# Add your application dependencies
target 'RainbowModuleExample' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."

  )

  # Pods for RainbowModuleExample
 permissions_path = '../node_modules/react-native-permissions/ios'
    # Use this helper to setup specific permissions
    setup_permissions([
      'Camera',
      'Contacts',
      'Microphone',
      'PhotoLibrary',
      'Notifications',
    ])
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    ) # Fix react-native libraries compatibility with the notification extension
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'

        end
      end
  end
end
